[package]
name = "httptest"
version = "0.1.0"
authors = ["Glenn Griffin <ggriffiniii@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
futures = "0.3"
tokio = { version = "0.2", features = ["macros"] }
crossbeam-channel = "0.4.0"
http = "0.2"
log = "0.4.8"
bstr = "0.2.8"
regex = "1.3.1"
url = "2.1.0"
serde_json = "1.0.44"
serde = "1.0.103"
serde_urlencoded = "0.6.1"

[dev-dependencies]
pretty_env_logger = "0.3.1"
